#!/usr/bin/env ruby

# This analyses all the level data and puts them all into chunks.
# Run this from the repository root!

# 8x8 is less to load and less likely to hitch.
# 16x16 compresses better even if we ignore pointer sizes (also compared against the vanilla RLE scheme).
# Let's go with 16x16 for now.
CHUNK_SIZE = 16
#CHUNK_SIZE = 8

# Using an indirect chunk pointer table and 2-byte indices actually makes things worse. (also tested with 8x8)
# So, use 3-byte pointers.
PER_PTR_COST = 3
PER_CHUNK_COST = 0

# Here's everything we need to load and their labels!
LAYOUT_SPECS = [
  ["LVLAYOUT_GHZ1_ENDING", "src/data/lv_ghz_1_ending.layout8"],
  ["LVLAYOUT_GHZ2", "src/data/lv_ghz_2.layout7"],
  ["LVLAYOUT_GHZ3", "src/data/lv_ghz_3.layout7"],
  ["LVLAYOUT_JUN1", "src/data/lv_jun_1.layout8"],
  ["LVLAYOUT_JUN2_special_4_8", "src/data/lv_jun_2_special_4_8.layout4"],
  ["LVLAYOUT_SCR1", "src/data/lv_scr_1.layout8"],
  ["LVLAYOUT_SCR2_main", "src/data/lv_scr_2_main.layout7"],
  ["LVLAYOUT_SCR2_upper", "src/data/lv_scr_2_upper.layout6"],
  ["LVLAYOUT_SCR2_lower", "src/data/lv_scr_2_lower.layout5"],
  ["LVLAYOUT_SCR3", "src/data/lv_scr_3.layout6"],
  ["LVLAYOUT_SKY2", "src/data/lv_sky_2.layout6"],
  ["LVLAYOUT_BRI1", "src/data/lv_bri_1.layout8"],
  ["LVLAYOUT_LAB1", "src/data/lv_lab_1.layout6"],
  ["LVLAYOUT_LAB2", "src/data/lv_lab_2.layout6"],
  ["LVLAYOUT_SKY1", "src/data/lv_sky_1.layout7"],
  ["LVLAYOUT_BRI2", "src/data/lv_bri_2.layout7"],
  ["LVLAYOUT_SKY3_endof_SKY2", "src/data/lv_sky_3_end_sky_2.layout6"],
  ["LVLAYOUT_JUN3", "src/data/lv_jun_3.layout6"],
  ["LVLAYOUT_LAB3", "src/data/lv_lab_3.layout6"],
  ["LVLAYOUT_BRI3", "src/data/lv_bri_3.layout7"],
  ["LVLAYOUT_SPECIAL_1_2_3_5_6_7", "src/data/lv_special_1_2_3_5_6_7.layout6"],
]

def main
  # Look at all files
  $next_chunk_idx = 0
  $used_chunks = {}

  $used_bytes = Set.new

  $total_rle_bytes = 0
  $total_chunked_bytes = 0

  puts ";; Autogenerated by ./tools/chunkalyser.rb - do not hand-edit!"
  LAYOUT_SPECS.each do |(layout_label, fname)|
    width_shift = fname[-1].to_i

    # Unpack RLE data
    #$used_chunks.clear # Fun fact, we save 23 8x8 chunks or 11 16x16 chunks if we share them between levels.
    rle_data = File.read(fname)
    $total_rle_bytes += rle_data.length
    unpacked_1d = unpack_rle_1d(rle_data)
    width = 1 << width_shift
    assert unpacked_1d.length % width == 0
    height = unpacked_1d.length / width
    unpacked_2d = level_1d_to_2d(unpacked_1d, width, height)

    # Build chunks
    prev_chunk_count = $next_chunk_idx
    ptr_list = []
    (height/CHUNK_SIZE).times do |cy|
      (width/CHUNK_SIZE).times do |cx|
        unc_chunk = extract_chunk_from_2d(unpacked_2d, cx*CHUNK_SIZE, cy*CHUNK_SIZE, CHUNK_SIZE, CHUNK_SIZE)
        chunk = newcmp_pack(unc_chunk)
        #chunk = ext_zx0_pack(unc_chunk)

        $total_chunked_bytes += PER_PTR_COST
        unless $used_chunks.has_key?(chunk)
          $total_chunked_bytes += PER_CHUNK_COST
          $total_chunked_bytes += chunk.length
          chunk_name = "chunk_#{($next_chunk_idx+0x10000).to_s(16).upcase[1..]}"
          $used_chunks[chunk] = chunk_name
          #pp chunk
          #puts chunk.map{|v| (v+0x100).to_s(16).upcase[1..]}.join("")
          puts ""
          puts ".SECTION \"base_#{chunk_name}\" SLOT 2 SUPERFREE"
          puts "#{chunk_name}:"
          puts ".DB " + chunk.map{|v| "$" + (v+0x100).to_s(16).upcase[1..]}.join(", ")
          puts ".ENDS"
          $next_chunk_idx += 1
        end
        ptr_list << $used_chunks[chunk]
      end
    end

    puts ""
    puts ".SECTION \"base_#{layout_label}\" SLOT 2 SUPERFREE"
    puts "#{layout_label}:"
    ptr_list.each do |ptr_name|
      puts ".DW #{ptr_name}"
      puts ".DB :#{ptr_name}"
    end
    puts ".ENDS"
    #unpacked_2d.each{|row| puts row.map{|v| (v+0x100).to_s(16).upcase[1..]}.join("")}
  end
  puts ""
  puts ";; TOTAL SIZE: #{$total_rle_bytes} -> #{$total_chunked_bytes}"

  # SANITY CHECK: Ensure E0 upwards are unused
  0x100.times do |i|
    assert (not $used_bytes.include? i) if i >= 0xDF
    #puts "unused #{i.to_s(16).upcase}" unless $used_bytes.include? i
  end
end

def assert(v)
  raise "assertion failed" if not v
end

def unpack_rle_1d(rle_data)
  unpacked_1d = []
  prev_rle_byte = -1
  awaiting_rle_byte = false
  rle_data.each_byte do |b|
    if awaiting_rle_byte then
      b += 0x100 if b == 0
      b.times { unpacked_1d << prev_rle_byte }
      prev_rle_byte = -1
      awaiting_rle_byte = false
    elsif b != prev_rle_byte
      unpacked_1d << b
      prev_rle_byte = b
      $used_bytes.add(b)
    else
      awaiting_rle_byte = true
    end
  end
  unpacked_1d << 0 while unpacked_1d.length < 4096
  assert unpacked_1d.length == 4096
  unpacked_1d
end

def level_1d_to_2d(unpacked_1d, width, height)
  (0...height).map do |y|
    (0...width).map do |x|
      unpacked_1d[x+(y*width)]
    end
  end
end

def extract_chunk_from_2d(unpacked_2d, x0, y0, lx, ly)
  (0...ly).map do |sy|
    (0...lx).map do |sx|
      unpacked_2d[y0+sy][x0+sx]
    end
  end.flatten
end

# A possible option. Gives better results for 16x16 but worse for 8x8.
# Must have ZX0 installed and in your PATH: https://github.com/einar-saukas/ZX0
def ext_zx0_pack(unc_chunk)
  begin
    File.write("zx0unc.tmp", unc_chunk.join)
    system("zx0", "zx0unc.tmp", "zx0cmp.tmp")
    File.read("zx0cmp.tmp").bytes
  ensure
    File.unlink("zx0cmp.tmp") rescue nil
    File.unlink("zx0unc.tmp") rescue nil
  end
end

def newcmp_pack(unc_chunk)
  # 00..DF = literal
  # E0..FF = 2..33 repeats of previous literal
  rle_runs = []
  unc_chunk.each do |b|
    if rle_runs.length == 0 or rle_runs[-1][0] != b
      rle_runs << [b, 1]
    else
      rle_runs[-1][1] += 1
    end
  end
  chunk = []
  rle_runs.each do |(b, count)|
    chunk << b
    count -= 1
    while count > 0
      # Check if we have any long runs
      if count < 2 then
        chunk << b
        count -= 1
      elsif count >= 33 then
        chunk << 0xFF
        count -= 33
      else
        chunk << 0xE0+(count-2)
        count -= count
      end
    end
  end
  chunk << 0xDF  # End-of-stream marker
  chunk
end

main
