#!/usr/bin/env ruby

# This analyses all the level data and puts them all into chunks.
# Run this from the repository root!
require "./tools/s1lib/all.rb"

# 8x8 is less to load and less likely to hitch.
# 16x16 compresses better even if we ignore pointer sizes (also compared against the vanilla RLE scheme).
# Let's go with 16x16 for now.
CHUNK_SIZE = 16
#CHUNK_SIZE = 8

# Using an indirect chunk pointer table and 2-byte indices actually makes things worse. (also tested with 8x8)
# So, use 3-byte pointers.
PER_PTR_COST = 3
PER_CHUNK_COST = 0

# Here's everything we need to load and their labels!
LAYOUT_SPECS = [
  LayoutSpec[name: "LVLAYOUT_GHZ1_ENDING", fname: "src/data/lv_ghz_1_ending.layout8"],
  LayoutSpec[name: "LVLAYOUT_GHZ2", fname: "src/data/lv_ghz_2.layout7"],
  LayoutSpec[name: "LVLAYOUT_GHZ3", fname: "src/data/lv_ghz_3.layout7"],
  LayoutSpec[name: "LVLAYOUT_JUN1", fname: "src/data/lv_jun_1.layout8"],
  LayoutSpec[name: "LVLAYOUT_JUN2_special_4_8", fname: "src/data/lv_jun_2_special_4_8.layout4"],
  LayoutSpec[name: "LVLAYOUT_SCR1", fname: "src/data/lv_scr_1.layout8"],
  LayoutSpec[name: "LVLAYOUT_SCR2_main", fname: "src/data/lv_scr_2_main.layout7"],
  LayoutSpec[name: "LVLAYOUT_SCR2_upper", fname: "src/data/lv_scr_2_upper.layout6"],
  LayoutSpec[name: "LVLAYOUT_SCR2_lower", fname: "src/data/lv_scr_2_lower.layout5"],
  LayoutSpec[name: "LVLAYOUT_SCR3", fname: "src/data/lv_scr_3.layout6"],
  LayoutSpec[name: "LVLAYOUT_SKY2", fname: "src/data/lv_sky_2.layout6"],
  LayoutSpec[name: "LVLAYOUT_BRI1", fname: "src/data/lv_bri_1.layout8"],
  LayoutSpec[name: "LVLAYOUT_LAB1", fname: "src/data/lv_lab_1.layout6"],
  LayoutSpec[name: "LVLAYOUT_LAB2", fname: "src/data/lv_lab_2.layout6"],
  LayoutSpec[name: "LVLAYOUT_SKY1", fname: "src/data/lv_sky_1.layout7"],
  LayoutSpec[name: "LVLAYOUT_BRI2", fname: "src/data/lv_bri_2.layout7"],
  LayoutSpec[name: "LVLAYOUT_SKY3_endof_SKY2", fname: "src/data/lv_sky_3_end_sky_2.layout6"],
  LayoutSpec[name: "LVLAYOUT_JUN3", fname: "src/data/lv_jun_3.layout6"],
  LayoutSpec[name: "LVLAYOUT_LAB3", fname: "src/data/lv_lab_3.layout6"],
  LayoutSpec[name: "LVLAYOUT_BRI3", fname: "src/data/lv_bri_3.layout7"],
  LayoutSpec[name: "LVLAYOUT_SPECIAL_1_2_3_5_6_7", fname: "src/data/lv_special_1_2_3_5_6_7.layout6"],
]

def main
  # Look at all files
  $next_chunk_idx = 0
  $used_chunks = {}

  $used_bytes = Set.new

  $total_rle_bytes = 0
  $total_chunked_bytes = 0

  puts ";; Autogenerated by ./tools/chunkalyser.rb - do not hand-edit!"
  LAYOUT_SPECS.each do |layout|
    # Build chunks
    prev_chunk_count = $next_chunk_idx
    ptr_list = []
    layout.each_chunk(CHUNK_SIZE) do |cx, cy, unc_chunk|
      chunk = newcmp_pack(unc_chunk)
      #chunk = ext_zx0_pack(unc_chunk)

      $total_chunked_bytes += PER_PTR_COST
      unless $used_chunks.has_key?(chunk)
        $total_chunked_bytes += PER_CHUNK_COST
        $total_chunked_bytes += chunk.length
        chunk_name = "chunk_#{($next_chunk_idx+0x10000).to_s(16).upcase[1..]}"
        $used_chunks[chunk] = chunk_name
        #pp chunk
        #puts chunk.map{|v| (v+0x100).to_s(16).upcase[1..]}.join("")
        puts ""
        puts ".SECTION \"base_#{chunk_name}\" SLOT 2 SUPERFREE"
        puts "#{chunk_name}:"
        puts ".DB " + chunk.map{|v| "$" + (v+0x100).to_s(16).upcase[1..]}.join(", ")
        puts ".ENDS"
        $next_chunk_idx += 1
      end
      ptr_list << $used_chunks[chunk]
    end

    puts ""
    puts ".SECTION \"base_#{layout.name}\" SLOT 2 SUPERFREE"
    puts "#{layout.name}:"
    ptr_list.each do |ptr_name|
      puts ".DW #{ptr_name}"
      puts ".DB :#{ptr_name}"
    end
    puts ".ENDS"
    #layout.unpacked_2d.each{|row| puts row.map{|v| (v+0x100).to_s(16).upcase[1..]}.join("")}
  end
  puts ""
  puts ";; TOTAL SIZE: #{$total_rle_bytes} -> #{$total_chunked_bytes}"

  # SANITY CHECK: Ensure E0 upwards are unused
  0x100.times do |i|
    assert (not $used_bytes.include? i) if i >= 0xDF
    #puts "unused #{i.to_s(16).upcase}" unless $used_bytes.include? i
  end
end

main
