#!/usr/bin/env ruby

# This analyses all the level data and puts them all into chunks.
# Run this from the repository root!
require "./tools/s1lib/all.rb"

# 8x8 is less to load and less likely to hitch.
# 16x16 compresses better even if we ignore pointer sizes (also compared against the vanilla RLE scheme).
# Let's go with 16x16 for now.
CHUNK_SIZE = 16
#CHUNK_SIZE = 8

# Using an indirect chunk pointer table and 2-byte indices actually makes things worse. (also tested with 8x8)
# So, use 3-byte pointers.
# Also we need a ramsave pointer too, of which 2 bytes is enough as RAM is limited to 8 KB.
PER_PTR_COST = 5
PER_CHUNK_COST = 0

# Here's everything we need to load and their labels!
LAYOUT_SPECS = [
  LayoutSpec[name: "LVLAYOUT_GHZ1_ENDING", fname: "src/data/lv_ghz_1_ending.layout8"],
  LayoutSpec[name: "LVLAYOUT_GHZ2", fname: "src/data/lv_ghz_2.layout7"],
  LayoutSpec[name: "LVLAYOUT_GHZ3", fname: "src/data/lv_ghz_3.layout7"],
  LayoutSpec[name: "LVLAYOUT_JUN1", fname: "src/data/lv_jun_1.layout8"],
  LayoutSpec[name: "LVLAYOUT_JUN2_special_4_8", fname: "src/data/lv_jun_2_special_4_8.layout4"],
  LayoutSpec[name: "LVLAYOUT_SCR1", fname: "src/data/lv_scr_1.layout8"],
  LayoutSpec[name: "LVLAYOUT_SCR2_main", fname: "src/data/lv_scr_2_main.layout7"],
  LayoutSpec[name: "LVLAYOUT_SCR2_upper", fname: "src/data/lv_scr_2_upper.layout6"],
  LayoutSpec[name: "LVLAYOUT_SCR2_lower", fname: "src/data/lv_scr_2_lower.layout5"],
  LayoutSpec[name: "LVLAYOUT_SCR3", fname: "src/data/lv_scr_3.layout6"],
  LayoutSpec[name: "LVLAYOUT_SKY2", fname: "src/data/lv_sky_2.layout6"],
  LayoutSpec[name: "LVLAYOUT_BRI1", fname: "src/data/lv_bri_1.layout8"],
  LayoutSpec[name: "LVLAYOUT_LAB1", fname: "src/data/lv_lab_1.layout6"],
  LayoutSpec[name: "LVLAYOUT_LAB2", fname: "src/data/lv_lab_2.layout6"],
  LayoutSpec[name: "LVLAYOUT_SKY1", fname: "src/data/lv_sky_1.layout7"],
  LayoutSpec[name: "LVLAYOUT_BRI2", fname: "src/data/lv_bri_2.layout7"],
  LayoutSpec[name: "LVLAYOUT_SKY3_endof_SKY2", fname: "src/data/lv_sky_3_end_sky_2.layout6"],
  LayoutSpec[name: "LVLAYOUT_JUN3", fname: "src/data/lv_jun_3.layout6"],
  LayoutSpec[name: "LVLAYOUT_LAB3", fname: "src/data/lv_lab_3.layout6"],
  LayoutSpec[name: "LVLAYOUT_BRI3", fname: "src/data/lv_bri_3.layout7"],
  LayoutSpec[name: "LVLAYOUT_SPECIAL_1_2_3_5_6_7", fname: "src/data/lv_special_1_2_3_5_6_7.layout6"],
]

def main
  $next_chunk_idx = 0
  $used_chunks = {}

  $next_ram_save_idx = 0

  $used_bytes = Set.new

  $total_rle_bytes = 0
  $total_chunked_bytes = 0
  $total_ram_save_bytes = 0

  outdata = ""
  outdata << ";; Autogenerated by ./tools/chunkalyser.rb - do not hand-edit!\n"
  LAYOUT_SPECS.each do |layout|
    # Build chunks
    prev_chunk_count = $next_chunk_idx
    ptr_list = []
    layout.each_chunk(CHUNK_SIZE) do |cx, cy, chunk|
      $total_chunked_bytes += PER_PTR_COST
      unless $used_chunks.has_key?(chunk)
        $total_chunked_bytes += PER_CHUNK_COST
        $total_chunked_bytes += chunk.compressed.length
        chunk_name = "chunk_#{($next_chunk_idx+0x10000).to_s(16).upcase[1..]}"
        $used_chunks[chunk] = chunk_name
        #pp chunk
        #puts chunk.map{|v| (v+0x100).to_s(16).upcase[1..]}.join("")
        outdata << "\n"
        outdata << chunk.emit_section(chunk_name)
        $next_chunk_idx += 1
      end
      ram_save_bytes = chunk.ram_save_byte_count
      if ram_save_bytes >= 1
        $total_ram_save_bytes += ram_save_bytes
        chunksave_name = "chunksave_#{($next_ram_save_idx+0x10000).to_s(16).upcase[1..]}"
        $next_ram_save_idx += 1
        outdata << "\n"
        outdata << chunk.emit_ramsection(chunksave_name)
        #puts ";; chunk #{$used_chunks[chunk]} bytes = #{ram_save_bytes}"
      else
        chunksave_name = 0
      end
      ptr_list << [$used_chunks[chunk], chunksave_name]
    end

    outdata << "\n"
    outdata << ".SECTION \"base_#{layout.name}\" SLOT 2 SUPERFREE\n"
    outdata << "#{layout.name}:\n"
    ptr_list.each do |(ptr_name, ramsave_name)|
      outdata << ".DW #{ramsave_name}\n"
      outdata << ".DW #{ptr_name}\n"
      outdata << ".DB :#{ptr_name}\n"
    end
    outdata << ".ENDS\n"
    #layout.unpacked_2d.each{|row| puts row.map{|v| (v+0x100).to_s(16).upcase[1..]}.join("")}
  end
  outdata << "\n"
  outdata << ";; TOTAL SIZE: #{$total_rle_bytes} -> #{$total_chunked_bytes}\n"
  outdata << ";; RAM CONSUMPTION: 3072 -> #{$total_ram_save_bytes}\n"

  # SANITY CHECK: Ensure E0 upwards are unused
  0x100.times do |i|
    assert (not $used_bytes.include? i) if i >= 0xDF  # reserved for our RLE compression
    assert (not $used_bytes.include? i) if i >= 0x7C and i <= 0x7F  # reserved in the original engine for ring purposes
    #puts "unused #{i.to_s(16).upcase}" unless $used_bytes.include? i
  end

  puts outdata
end

main
